/**
 * Product barcodes. A SKU's barcode is either an EAN-13 (validated by its
 * check digit) or any other value a Code 128 scanner can send: printable
 * ASCII without spaces, up to 48 characters. Internal barcodes generated by
 * the system are EAN-13s in the in-store range (first digit 2).
 */

export const BARCODE_MAX_LENGTH = 48;

const BARCODE_PATTERN = /^[!-~]{1,48}$/;
const EAN13_PATTERN = /^\d{13}$/;

/** Prefix of internally generated EAN-13s (GS1 "restricted circulation" range 20–29). */
export const INTERNAL_EAN_PREFIX = "2";

/** Largest sequence that fits after the prefix (11 digits). */
export const MAX_INTERNAL_SEQUENCE = 99_999_999_999;

/** EAN-13 check digit of the first 12 digits (weights 1, 3, 1, 3, …). */
export function ean13CheckDigit(first12: string): number {
  if (!/^\d{12}$/.test(first12)) throw new Error("An EAN-13 check digit needs exactly 12 digits.");
  const sum = [...first12].reduce((total, digit, index) => total + Number(digit) * (index % 2 === 0 ? 1 : 3), 0);
  return (10 - (sum % 10)) % 10;
}

export function isValidEan13(value: string): boolean {
  return EAN13_PATTERN.test(value) && ean13CheckDigit(value.slice(0, 12)) === Number(value[12]);
}

/** The internal EAN-13 for a sequence number, e.g. 1 → "2000000000015". */
export function internalEan13(sequence: number): string {
  if (!Number.isInteger(sequence) || sequence < 1 || sequence > MAX_INTERNAL_SEQUENCE) {
    throw new Error(`Barcode sequence out of range: ${sequence}`);
  }
  const first12 = INTERNAL_EAN_PREFIX + String(sequence).padStart(11, "0");
  return first12 + ean13CheckDigit(first12);
}

/** Why a barcode is not acceptable, or null when it is. 13 digits must be a valid EAN-13. */
export function barcodeProblem(value: string): string | null {
  if (!BARCODE_PATTERN.test(value)) {
    return `Use up to ${BARCODE_MAX_LENGTH} letters, digits or symbols, without spaces.`;
  }
  if (EAN13_PATTERN.test(value) && !isValidEan13(value)) return "This EAN-13 has a wrong check digit.";
  return null;
}

/**
 * The product a scanned value stands for among those already loaded: its
 * barcode (exact), else its code (case-insensitive). Mirrors the server lookup.
 */
export function findByScanCode<T extends { code: string; barcode: string | null }>(items: T[], scanned: string): T | undefined {
  const value = scanned.trim();
  if (!value) return undefined;
  const upper = value.toUpperCase();
  return items.find((item) => item.barcode === value) ?? items.find((item) => item.code.toUpperCase() === upper);
}

/** Symbology to print a barcode value in: EAN-13 when it is one, Code 128 otherwise. */
export function barcodeSymbology(value: string): "ean13" | "code128" {
  return isValidEan13(value) ? "ean13" : "code128";
}
