-- Phase 4C: notifications (rules, transactional outbox, in-app centre),
-- DB-backed settings, slow-moving alerts and the daily checklist.
--
-- Generated by prisma migrate diff; constraints Prisma cannot express and the
-- live-update trigger for in-app notifications are appended at the end.

-- CreateEnum
CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP', 'EMAIL', 'WHATSAPP');

-- CreateEnum
CREATE TYPE "NotificationAlertType" AS ENUM ('LOW_STOCK', 'SLOW_MOVING');

-- CreateEnum
CREATE TYPE "NotificationFrequency" AS ENUM ('IMMEDIATE', 'DAILY_DIGEST');

-- CreateEnum
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'SENT', 'FAILED', 'SKIPPED');

-- AlterTable
ALTER TABLE "stock_alert" ADD COLUMN     "days_idle" INTEGER;

-- CreateTable
CREATE TABLE "app_setting" (
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_by_id" UUID,

    CONSTRAINT "app_setting_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "scheduled_job_run" (
    "key" TEXT NOT NULL,
    "last_run_on" DATE NOT NULL,
    "last_run_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "scheduled_job_run_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "notification_rule" (
    "alert_type" "NotificationAlertType" NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT true,
    "frequency" "NotificationFrequency" NOT NULL DEFAULT 'IMMEDIATE',
    "digest_time" TEXT NOT NULL DEFAULT '09:00',
    "in_app_enabled" BOOLEAN NOT NULL DEFAULT true,
    "email_enabled" BOOLEAN NOT NULL DEFAULT false,
    "whatsapp_enabled" BOOLEAN NOT NULL DEFAULT false,
    "in_app_roles" "RoleCode"[] DEFAULT ARRAY[]::"RoleCode"[],
    "in_app_user_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "email_recipients" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "whatsapp_recipients" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_by_id" UUID,

    CONSTRAINT "notification_rule_pkey" PRIMARY KEY ("alert_type")
);

-- CreateTable
CREATE TABLE "notification_outbox" (
    "id" UUID NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "recipient" TEXT NOT NULL,
    "alert_type" "NotificationAlertType",
    "stock_alert_id" UUID,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "link" TEXT,
    "payload" JSONB,
    "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "locked_until" TIMESTAMPTZ(3),
    "last_error" TEXT,
    "provider_message_id" TEXT,
    "sent_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "notification_outbox_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_attempt" (
    "id" UUID NOT NULL,
    "outbox_id" UUID NOT NULL,
    "attempt_no" INTEGER NOT NULL,
    "status" "NotificationStatus" NOT NULL,
    "error" TEXT,
    "duration_ms" INTEGER,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notification_attempt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "alert_type" "NotificationAlertType",
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "link" TEXT,
    "read_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "checklist_task" (
    "id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "roles" "RoleCode"[] DEFAULT ARRAY[]::"RoleCode"[],
    "due_time" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "checklist_task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "checklist_task_completion" (
    "task_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "day" DATE NOT NULL,
    "completed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "checklist_task_completion_pkey" PRIMARY KEY ("task_id","user_id","day")
);

-- CreateTable
CREATE TABLE "checklist_view" (
    "user_id" UUID NOT NULL,
    "day" DATE NOT NULL,
    "seen_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "checklist_view_pkey" PRIMARY KEY ("user_id","day")
);

-- CreateIndex
CREATE INDEX "notification_outbox_status_next_attempt_at_idx" ON "notification_outbox"("status", "next_attempt_at");

-- CreateIndex
CREATE INDEX "notification_outbox_stock_alert_id_idx" ON "notification_outbox"("stock_alert_id");

-- CreateIndex
CREATE INDEX "notification_outbox_created_at_idx" ON "notification_outbox"("created_at");

-- CreateIndex
CREATE INDEX "notification_attempt_outbox_id_idx" ON "notification_attempt"("outbox_id");

-- CreateIndex
CREATE INDEX "notification_user_id_read_at_created_at_idx" ON "notification"("user_id", "read_at", "created_at");

-- CreateIndex
CREATE INDEX "checklist_task_completion_user_id_day_idx" ON "checklist_task_completion"("user_id", "day");

-- AddForeignKey
ALTER TABLE "notification_outbox" ADD CONSTRAINT "notification_outbox_stock_alert_id_fkey" FOREIGN KEY ("stock_alert_id") REFERENCES "stock_alert"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_attempt" ADD CONSTRAINT "notification_attempt_outbox_id_fkey" FOREIGN KEY ("outbox_id") REFERENCES "notification_outbox"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification" ADD CONSTRAINT "notification_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "checklist_task" ADD CONSTRAINT "checklist_task_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "checklist_task_completion" ADD CONSTRAINT "checklist_task_completion_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "checklist_task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "checklist_task_completion" ADD CONSTRAINT "checklist_task_completion_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "checklist_view" ADD CONSTRAINT "checklist_view_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- Hand-written: integrity rules the services also enforce.
-- ---------------------------------------------------------------------------

ALTER TABLE "notification_rule"
  ADD CONSTRAINT "notification_rule_digest_time_format" CHECK ("digest_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');

ALTER TABLE "checklist_task"
  ADD CONSTRAINT "checklist_task_due_time_format" CHECK ("due_time" IS NULL OR "due_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  ADD CONSTRAINT "checklist_task_title_not_blank" CHECK (btrim("title") <> '');

ALTER TABLE "notification_outbox"
  ADD CONSTRAINT "notification_outbox_attempts_non_negative" CHECK ("attempts" >= 0);

ALTER TABLE "stock_alert"
  ADD CONSTRAINT "stock_alert_type_known" CHECK ("alert_type" IN ('LOW_STOCK', 'SLOW_MOVING'));

-- ---------------------------------------------------------------------------
-- Live updates: new in-app notifications are announced on the change feed
-- (committed inserts only), so open screens refresh their bell count. The
-- worker writes notifications without an audit entry, like Tally results.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION "notify_change"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_TABLE_NAME = 'audit_log' THEN
    PERFORM pg_notify('margix_changes', json_build_object('entity', NEW."entity_type", 'action', NEW."action")::text);
  ELSIF TG_TABLE_NAME = 'notification' THEN
    PERFORM pg_notify('margix_changes', json_build_object('entity', 'Notification', 'action', 'NOTIFICATION_CREATED')::text);
  ELSE
    PERFORM pg_notify('margix_changes', json_build_object('entity', 'TallySyncJob', 'action', 'TALLY_JOB_' || NEW."status")::text);
  END IF;
  RETURN NULL;
END;
$$;

-- Once per statement: a batch of notifications causes one refresh.
CREATE TRIGGER "notification_notify_change"
AFTER INSERT ON "notification"
FOR EACH STATEMENT
EXECUTE FUNCTION "notify_change"();

